import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./custom_components/Navbar";
import Footer from "./custom_components/Footer";
import Chatbot from "./custom_components/Chatbot";

import { ReactNode } from 'react';

const inter = Inter({ subsets: ["latin"] });



export const metadata = {
  title: "Space-slam",
  description: "Generated by create next ",
};




export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>



        <Navbar />

        <div className="min-h-screen bg-black text-white">


          {children}


          <Footer />

        </div>
        <Chatbot />


      </body>
    </html>
  );
}
